/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/omnimetron/cpu_temp/CpuTempDataSomeIPStubAdapter.hpp>
#include <v1/omnimetron/cpu_temp/CpuTempData.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace omnimetron {
namespace cpu_temp {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createCpuTempDataSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< CpuTempDataSomeIPStubAdapter<::v1::omnimetron::cpu_temp::CpuTempDataStub>>(_address, _connection, _stub);
}

void initializeCpuTempDataSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:omnimetron.cpu_temp.CpuTempData:v1_0:omnimetron.cpu_temp.CpuTempData",
         0x1b21, 0x567d, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "omnimetron.cpu_temp.CpuTempData:v1_0",
        &createCpuTempDataSomeIPStubAdapter);
}

INITIALIZER(registerCpuTempDataSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeCpuTempDataSomeIPStubAdapter);
}

} // namespace cpu_temp
} // namespace omnimetron
} // namespace v1
