/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_OMNIMETRON_CPU_TEMP_Cpu_Temp_Data_STUB_DEFAULT_HPP_
#define V1_OMNIMETRON_CPU_TEMP_Cpu_Temp_Data_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/omnimetron/cpu_temp/CpuTempDataStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace omnimetron {
namespace cpu_temp {

/**
 * Provides a default implementation for CpuTempDataStubRemoteEvent and
 * CpuTempDataStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT CpuTempDataStubDefault
    : public virtual CpuTempDataStub {
public:
    COMMONAPI_EXPORT CpuTempDataStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(CpuTempData::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT CpuTempDataStubRemoteEvent* initStubAdapter(const std::shared_ptr< CpuTempDataStubAdapter> &_adapter) {
        CommonAPI::Stub<CpuTempDataStubAdapter, CpuTempDataStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual void requestCpuTempData(const std::shared_ptr<CommonAPI::ClientId> _client, requestCpuTempDataReply_t _reply) {
        (void)_client;
        float temperature = 0.0f;
        _reply(temperature);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual CpuTempDataStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(CpuTempDataStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        CpuTempDataStubDefault *defaultStub_;
    };
protected:
    CpuTempDataStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace cpu_temp
} // namespace omnimetron
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_OMNIMETRON_CPU_TEMP_Cpu_Temp_Data_STUB_DEFAULT
