/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_OMNIMETRON_CPU_TEMP_CPU_TEMP_DATA_HPP_
#define V1_OMNIMETRON_CPU_TEMP_CPU_TEMP_DATA_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Types.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace omnimetron {
namespace cpu_temp {

class CpuTempData {
public:
    virtual ~CpuTempData() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* CpuTempData::getInterface() {
    return ("omnimetron.cpu_temp.CpuTempData:v1_0");
}

CommonAPI::Version CpuTempData::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}


} // namespace cpu_temp
} // namespace omnimetron
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_OMNIMETRON_CPU_TEMP_CPU_TEMP_DATA_HPP_
