/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/omnimetron/cpu_temp/CpuTempDataSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace omnimetron {
namespace cpu_temp {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createCpuTempDataSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< CpuTempDataSomeIPProxy>(_address, _connection);
}

void initializeCpuTempDataSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:omnimetron.cpu_temp.CpuTempData:v1_0:omnimetron.cpu_temp.CpuTempData",
        0x1b21, 0x567d, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "omnimetron.cpu_temp.CpuTempData:v1_0",
        &createCpuTempDataSomeIPProxy);
}

INITIALIZER(registerCpuTempDataSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeCpuTempDataSomeIPProxy);
}

CpuTempDataSomeIPProxy::CpuTempDataSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection)
{
}

CpuTempDataSomeIPProxy::~CpuTempDataSomeIPProxy() {
}



void CpuTempDataSomeIPProxy::requestCpuTempData(CommonAPI::CallStatus &_internalCallStatus, float &_temperature, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_temperature(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_temperature);
    _temperature = deploy_temperature.getValue();
}

std::future<CommonAPI::CallStatus> CpuTempDataSomeIPProxy::requestCpuTempDataAsync(RequestCpuTempDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_temperature(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< float, CommonAPI::EmptyDeployment > _temperature) {
            if (_callback)
                _callback(_internalCallStatus, _temperature.getValue());
        },
        std::make_tuple(deploy_temperature));
}

void CpuTempDataSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> CpuTempDataSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace cpu_temp
} // namespace omnimetron
} // namespace v1
