/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_OMNIMETRON_CPU_CPU_USAGE_DATA_SOMEIP_STUB_ADAPTER_HPP_
#define V1_OMNIMETRON_CPU_CPU_USAGE_DATA_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/omnimetron/cpu/CpuUsageDataStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace omnimetron {
namespace cpu {

template <typename _Stub = ::v1::omnimetron::cpu::CpuUsageDataStub, typename... _Stubs>
class CpuUsageDataSomeIPStubAdapterInternal
    : public virtual CpuUsageDataStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< CpuUsageDataSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> CpuUsageDataSomeIPStubAdapterHelper;

    ~CpuUsageDataSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        CpuUsageDataSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::omnimetron::cpu::CpuUsageDataStub,
        CommonAPI::Version
    > getCpuUsageDataInterfaceVersionStubDispatcher;

    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::omnimetron::cpu::CpuUsageDataStub,
        std::tuple< >,
        std::tuple< float>,
        std::tuple< >,
        std::tuple< CommonAPI::EmptyDeployment>
    > requestCpuUsageDataStubDispatcher;
    
    CpuUsageDataSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        CpuUsageDataSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< CpuUsageDataStub>(_stub)),
        getCpuUsageDataInterfaceVersionStubDispatcher(&CpuUsageDataStub::lockInterfaceVersionAttribute, &CpuUsageDataStub::getInterfaceVersion, false, true),
        requestCpuUsageDataStubDispatcher(
            &CpuUsageDataStub::requestCpuUsageData,
            false,
            _stub->hasElement(0),
            std::make_tuple(),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)))
        
    {
        CpuUsageDataSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &requestCpuUsageDataStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void CpuUsageDataSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void CpuUsageDataSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::omnimetron::cpu::CpuUsageDataStub, typename... _Stubs>
class CpuUsageDataSomeIPStubAdapter
    : public CpuUsageDataSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    CpuUsageDataSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          CpuUsageDataSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace cpu
} // namespace omnimetron
} // namespace v1

#endif // V1_OMNIMETRON_CPU_Cpu_Usage_Data_SOMEIP_STUB_ADAPTER_HPP_
