/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_OMNIMETRON_CPU_Cpu_Usage_Data_PROXY_HPP_
#define V1_OMNIMETRON_CPU_Cpu_Usage_Data_PROXY_HPP_

#include <v1/omnimetron/cpu/CpuUsageDataProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace omnimetron {
namespace cpu {

template <typename ... _AttributeExtensions>
class CpuUsageDataProxy
    : virtual public CpuUsageData,
      virtual public CpuUsageDataProxyBase,
      virtual public _AttributeExtensions... {
public:
    CpuUsageDataProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~CpuUsageDataProxy();

    typedef ::v1::omnimetron::cpu::CpuUsageData InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls requestCpuUsageData with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void requestCpuUsageData(CommonAPI::CallStatus &_internalCallStatus, float &_usage, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls requestCpuUsageData with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> requestCpuUsageDataAsync(RequestCpuUsageDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< CpuUsageDataProxyBase> delegate_;
};

typedef CpuUsageDataProxy<> CpuUsageDataProxyDefault;


//
// CpuUsageDataProxy Implementation
//
template <typename ... _AttributeExtensions>
CpuUsageDataProxy<_AttributeExtensions...>::CpuUsageDataProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< CpuUsageDataProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< CpuUsageDataProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
CpuUsageDataProxy<_AttributeExtensions...>::~CpuUsageDataProxy() {
}

template <typename ... _AttributeExtensions>
void CpuUsageDataProxy<_AttributeExtensions...>::requestCpuUsageData(CommonAPI::CallStatus &_internalCallStatus, float &_usage, const CommonAPI::CallInfo *_info) {
    delegate_->requestCpuUsageData(_internalCallStatus, _usage, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> CpuUsageDataProxy<_AttributeExtensions...>::requestCpuUsageDataAsync(RequestCpuUsageDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->requestCpuUsageDataAsync(_callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &CpuUsageDataProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool CpuUsageDataProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool CpuUsageDataProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& CpuUsageDataProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& CpuUsageDataProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> CpuUsageDataProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace cpu
} // namespace omnimetron
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_OMNIMETRON_CPU_Cpu_Usage_Data_PROXY_HPP_
