/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_OMNIMETRON_MEMORY_Memory_Usage_Data_PROXY_HPP_
#define V1_OMNIMETRON_MEMORY_Memory_Usage_Data_PROXY_HPP_

#include <v1/omnimetron/memory/MemoryUsageDataProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace omnimetron {
namespace memory {

template <typename ... _AttributeExtensions>
class MemoryUsageDataProxy
    : virtual public MemoryUsageData,
      virtual public MemoryUsageDataProxyBase,
      virtual public _AttributeExtensions... {
public:
    MemoryUsageDataProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~MemoryUsageDataProxy();

    typedef ::v1::omnimetron::memory::MemoryUsageData InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * Calls requestMemoryUsageData with synchronous semantics.
     *
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void requestMemoryUsageData(CommonAPI::CallStatus &_internalCallStatus, float &_usageMB, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls requestMemoryUsageData with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> requestMemoryUsageDataAsync(RequestMemoryUsageDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< MemoryUsageDataProxyBase> delegate_;
};

typedef MemoryUsageDataProxy<> MemoryUsageDataProxyDefault;


//
// MemoryUsageDataProxy Implementation
//
template <typename ... _AttributeExtensions>
MemoryUsageDataProxy<_AttributeExtensions...>::MemoryUsageDataProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< MemoryUsageDataProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< MemoryUsageDataProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
MemoryUsageDataProxy<_AttributeExtensions...>::~MemoryUsageDataProxy() {
}

template <typename ... _AttributeExtensions>
void MemoryUsageDataProxy<_AttributeExtensions...>::requestMemoryUsageData(CommonAPI::CallStatus &_internalCallStatus, float &_usageMB, const CommonAPI::CallInfo *_info) {
    delegate_->requestMemoryUsageData(_internalCallStatus, _usageMB, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> MemoryUsageDataProxy<_AttributeExtensions...>::requestMemoryUsageDataAsync(RequestMemoryUsageDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->requestMemoryUsageDataAsync(_callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &MemoryUsageDataProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool MemoryUsageDataProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool MemoryUsageDataProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& MemoryUsageDataProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& MemoryUsageDataProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> MemoryUsageDataProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace memory
} // namespace omnimetron
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_OMNIMETRON_MEMORY_Memory_Usage_Data_PROXY_HPP_
