/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/omnimetron/memory/MemoryUsageDataSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace omnimetron {
namespace memory {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createMemoryUsageDataSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< MemoryUsageDataSomeIPProxy>(_address, _connection);
}

void initializeMemoryUsageDataSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:omnimetron.memory.MemoryUsageData:v1_0:omnimetron.memory.MemoryUsageData",
        0x1b20, 0x567c, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "omnimetron.memory.MemoryUsageData:v1_0",
        &createMemoryUsageDataSomeIPProxy);
}

INITIALIZER(registerMemoryUsageDataSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeMemoryUsageDataSomeIPProxy);
}

MemoryUsageDataSomeIPProxy::MemoryUsageDataSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection)
{
}

MemoryUsageDataSomeIPProxy::~MemoryUsageDataSomeIPProxy() {
}



void MemoryUsageDataSomeIPProxy::requestMemoryUsageData(CommonAPI::CallStatus &_internalCallStatus, float &_usageMB, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_usageMB(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        _internalCallStatus,
        deploy_usageMB);
    _usageMB = deploy_usageMB.getValue();
}

std::future<CommonAPI::CallStatus> MemoryUsageDataSomeIPProxy::requestMemoryUsageDataAsync(RequestMemoryUsageDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_usageMB(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                float,
                CommonAPI::EmptyDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x1),
        false,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< float, CommonAPI::EmptyDeployment > _usageMB) {
            if (_callback)
                _callback(_internalCallStatus, _usageMB.getValue());
        },
        std::make_tuple(deploy_usageMB));
}

void MemoryUsageDataSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> MemoryUsageDataSomeIPProxy::getCompletionFuture() {
    return CommonAPI::SomeIP::Proxy::getCompletionFuture();
}

} // namespace memory
} // namespace omnimetron
} // namespace v1
